### ISSUE TITLE
Workflow Commons 2.1.0 not working correct with Mendix 9.12.0

### ISSUE THREAD

**Issue by patrickverhoevenappronto** [mendix/WorkflowCommons#8]
Hi,

Today I run into an error with Mendix workflow in 9.12 in combi with Workflow Commons 2.1.0. I  have created a blank app and have created the simple workflow from the Academy course. I get an error when e.g. complete a task or assign a user.

After downgrading the Workflow Commons to version 2.0.1 everything works fine.

Stack trace:

com.mendix.systemwideinterfaces.MendixRuntimeException: Unable to find objects for guids: HashSet(3096224743817317)
	at com.mendix.webui.actions.client.RegularClientActions$.commit(RegularClientActions.scala:35)
	at com.mendix.webui.actions.client.CoreClientActionsRegistry.$anonfun$coreClientActionMap$1(CoreClientActionsRegistry.scala:20)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$.$anonfun$liftEither$1(RegularClientAction.scala:30)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.$anonfun$apply$4(RegularClientAction.scala:56)
	at com.mendix.webui.requesthandling.helpers.StateHandling.withState(StateHandling.scala:42)
	at com.mendix.webui.requesthandling.helpers.StateHandling.withState$(StateHandling.scala:39)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.withState(RegularClientAction.scala:46)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.apply(RegularClientAction.scala:54)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.apply(RegularClientAction.scala:46)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$3(RegularClientAction.scala:113)
	at scala.util.Try$.apply(Try.scala:210)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$2(RegularClientAction.scala:113)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$2$adapted(RegularClientAction.scala:111)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.$anonfun$inContext$5(ContextHandling.scala:57)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.mendix.basis.actionmanagement.ActionMonitoring$.$anonfun$monitor$1(ActionMonitoring.scala:49)
	at com.mendix.util.classloading.Runner$.withContextClassLoader(Runner.scala:20)
	at com.mendix.basis.actionmanagement.ActionMonitoring$.monitor(ActionMonitoring.scala:49)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext(ContextHandling.scala:57)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext$(ContextHandling.scala:31)
	at com.mendix.webui.actions.client.RegularClientAction.inContext(RegularClientAction.scala:87)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext(ContextHandling.scala:28)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext$(ContextHandling.scala:20)
	at com.mendix.webui.actions.client.RegularClientAction.inContext(RegularClientAction.scala:87)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$1(RegularClientAction.scala:111)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest(ProfileHandling.scala:14)
	at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest$(ProfileHandling.scala:10)
	at com.mendix.webui.actions.client.RegularClientAction.profileRequest(RegularClientAction.scala:87)
	at com.mendix.webui.actions.client.RegularClientAction.execute(RegularClientAction.scala:108)
	at com.mendix.webui.requesthandling.ClientRequestHandler.handleAction(ClientRequestHandler.scala:106)
	at com.mendix.webui.requesthandling.ClientRequestHandler.processRequest(ClientRequestHandler.scala:79)
	at com.mendix.externalinterface.connector.RequestHandler.doProcessRequest(RequestHandler.java:37)
	at com.mendix.external.connector.MxRuntimeConnector.$anonfun$processRequest$1(MxRuntimeConnector.scala:50)
	at com.mendix.external.connector.MxRuntimeConnector.$anonfun$processRequest$1$adapted(MxRuntimeConnector.scala:50)
	at com.mendix.util.classloading.Runner$.withContextClassLoader(Runner.scala:20)
	at com.mendix.external.connector.MxRuntimeConnector.processRequest(MxRuntimeConnector.scala:50)
	at com.mendix.basis.impl.MxRuntimeImpl.processRequest(MxRuntimeImpl.scala:223)
	at com.mendix.m2ee.appcontainer.server.handler.RuntimeServlet.service(RuntimeServlet.scala:25)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:230)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:834)

Any idea what could be the problem?

Regards,
Patrick

**Comment by allard-mx** [comment]
Hi Patrick,

Thank you for raising the issue. We will look into this. Could you share the project in which this error occurs? Thank you in advance!

**Comment by patrickverhoevenappronto** [comment]
Hi Allard,

I have send you an invite. At this moment version 2.0.1 of WorkflowCommons in the app. To reproduce you have to update to version 2.1.0. 

Regards,
Patrick

**Comment by allard-mx** [comment]
Hi Patrick,

I received the invitation, thanks! For our information, when you tested this using WorkflowCommons 2.1.0, did you configure the event microflows as described in the module readme?

Kind regards,

Allard
